### ISSUE TITLE
Save subtitle as... wrong default filter.

### ISSUE THREAD

**Issue by CM630** [URUWorks/TeroSubtitler#361]
**Describe the bug**

**To Reproduce**
1. Main menu -> File -> Save subtitle as...
2. Save the subtitles with extension _.sub_
3. Main menu -> File -> Save subtitle as...

**Expected behavior**
On step 3: The file filter is set to to the one of the subs, in this case _.sub_

**Current behavior**
On step 3: The filter is set _.srt_

**Screenshots/Video**
If applicable, add screenshots/video to help explain your problem.

**Desktop (please complete the following information):**
 - OS: All
 - Version: 1.0.2.0

**Additional context**

**Comment by chenlung** [comment]
Filter > Extension

?

**Comment by CM630** [comment]
Odd... step seems to have failed for VTT. But is seems to work now, I have fixed only the misbehaviour on step 3.

**Comment by CM630** [comment]
Fixed in source, not yet comitted. Should be v1.0.2.0 (x.x.2024).

**Comment by chenlung** [comment]
Despite 'OS: All', this was possibly specific to Linux? I think I can still reproduce on Mac 10.12.6, for example.

Before step 1, are we to create a new project or open a specific file format?

Might be a duplicate of [this](https://github.com/URUWorks/TeroSubtitler/issues/324)?
